theme: jekyll-theme-minimal
title: Welcome to our project hommepage!
description: View the different 360 degree pictures of the void decks at Block 485B and Block 499C. 

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
